Fixes CVE-2022-41323.

Internationalized URLs were subject to potential denial of service attack via
the locale parameter. This is now escaped to avoid this possibility.

Backported from upstream:
https://github.com/django/django/commit/5b6b257fa7ec37ff27965358800c67e2dd11c924

--- Django-2.2.28/django/urls/resolvers.py
+++ Django-2.2.28/django/urls/resolvers.py
@@ -289,7 +289,7 @@ def __init__(self, prefix_default_language=True):
     @property
     def regex(self):
         # This is only used by reverse() and cached in _reverse_dict.
-        return re.compile(self.language_prefix)
+        return re.compile(re.escape(self.language_prefix))
 
     @property
     def language_prefix(self):
--- Django-2.2.28/tests/i18n/patterns/tests.py
+++ Django-2.2.28/tests/i18n/patterns/tests.py
@@ -163,6 +163,12 @@ def test_translate_url_utility(self):
             self.assertEqual(translate_url('/nl/gebruikers/', 'en'), '/en/users/')
             self.assertEqual(translation.get_language(), 'nl')
 
+    def test_locale_not_interepreted_as_regex(self):
+        with translation.override("e("):
+            # Would previously error:
+            # re.error: missing ), unterminated subpattern at position 1
+            reverse("users")
+
 
 class URLNamespaceTests(URLTestCaseBase):
     """
